// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: employees.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeManagementClient is the client API for EmployeeManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeManagementClient interface {
	CreateNewEmployee(ctx context.Context, in *NewEmployee, opts ...grpc.CallOption) (*Employee, error)
}

type employeeManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeManagementClient(cc grpc.ClientConnInterface) EmployeeManagementClient {
	return &employeeManagementClient{cc}
}

func (c *employeeManagementClient) CreateNewEmployee(ctx context.Context, in *NewEmployee, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/employees.EmployeeManagement/CreateNewEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeManagementServer is the server API for EmployeeManagement service.
// All implementations must embed UnimplementedEmployeeManagementServer
// for forward compatibility
type EmployeeManagementServer interface {
	CreateNewEmployee(context.Context, *NewEmployee) (*Employee, error)
	mustEmbedUnimplementedEmployeeManagementServer()
}

// UnimplementedEmployeeManagementServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeManagementServer struct {
}

func (UnimplementedEmployeeManagementServer) CreateNewEmployee(context.Context, *NewEmployee) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewEmployee not implemented")
}
func (UnimplementedEmployeeManagementServer) mustEmbedUnimplementedEmployeeManagementServer() {}

// UnsafeEmployeeManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeManagementServer will
// result in compilation errors.
type UnsafeEmployeeManagementServer interface {
	mustEmbedUnimplementedEmployeeManagementServer()
}

func RegisterEmployeeManagementServer(s grpc.ServiceRegistrar, srv EmployeeManagementServer) {
	s.RegisterService(&EmployeeManagement_ServiceDesc, srv)
}

func _EmployeeManagement_CreateNewEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmployee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeManagementServer).CreateNewEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employees.EmployeeManagement/CreateNewEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeManagementServer).CreateNewEmployee(ctx, req.(*NewEmployee))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeManagement_ServiceDesc is the grpc.ServiceDesc for EmployeeManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employees.EmployeeManagement",
	HandlerType: (*EmployeeManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewEmployee",
			Handler:    _EmployeeManagement_CreateNewEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employees.proto",
}
